import {
  Palette,
  Zap,
  Sparkles,
  Gamepad2,
  Waves,
  TreePine,
  Coffee,
  Cpu,
  Leaf,
  Accessibility,
  Brain,
  Headphones,
  Shield,
  Smartphone,
} from "lucide-react"
import type { CoderProfile } from "@/lib/types"

export const coderProfiles: CoderProfile[] = [
  {
    id: "1",
    name: "Miyazaki Coder",
    vibe: "Whimsical Studio Ghibli",
    platform: "desktop",
    bio: "Creating magical user experiences with React and animations.",
    fullBio:
      "I specialize in creating enchanting full-stack applications that feel like stepping into a Studio Ghibli film. With 5+ years of experience in React, Node.js, and modern web technologies, I bring stories to life through code. My passion lies in blending beautiful aesthetics with robust functionality, ensuring every user interaction is a delightful experience. I'm always exploring new ways to animate interfaces and create immersive digital worlds.",
    location: "Tokyo, Japan",
    timezone: "JST",
    rating: 4.9,
    reviews: 127,
    projects: 42,
    likes: 328,
    status: "Available",
    avatar: "/images/miyazaki_coder.jpeg",
    themeIcon: "🌸",
    skills: [
      "React",
      "Next.js",
      "Node.js",
      "TypeScript",
      "Framer Motion",
      "Three.js",
      "PostgreSQL",
      "CSS Animations",
      "UI/UX Design",
      "Storytelling",
    ],
    workExperience: [
      {
        company: "Studio Digital Dreams",
        role: "Senior Full-Stack Developer",
        duration: "2022 - Present",
        location: "Tokyo, Japan",
        description:
          "Lead developer for interactive storytelling platforms. Built immersive web experiences for major entertainment clients using React, Node.js, and Three.js. Mentored junior developers and established animation best practices.",
        technologies: ["React", "Node.js", "Three.js", "PostgreSQL", "AWS"],
        companyLogo: "/generic-studio-logo.png",
      },
      {
        company: "Anime Interactive Co.",
        role: "Frontend Developer",
        duration: "2020 - 2022",
        location: "Tokyo, Japan",
        description:
          "Developed animated web applications for anime studios. Specialized in creating smooth, performant animations and interactive character experiences. Collaborated with designers to bring static designs to life.",
        technologies: ["React", "GSAP", "CSS3", "JavaScript", "Figma"],
        companyLogo: "/anime-company.png",
      },
      {
        company: "Creative Web Solutions",
        role: "Junior Developer",
        duration: "2019 - 2020",
        location: "Tokyo, Japan",
        description:
          "Started my journey building responsive websites and learning modern JavaScript frameworks. Gained experience in full-stack development and agile methodologies.",
        technologies: ["HTML", "CSS", "JavaScript", "PHP", "MySQL"],
        companyLogo: "/web-solutions.png",
      },
    ],
    compensation: {
      hourlyRate: "$75 - $120/hour",
      projectRate: "$5,000 - $25,000",
      availability: "30-40 hours/week",
      preferredEngagement: "Both",
    },
    testimonials: [
      {
        id: "t1",
        reviewerName: "Sarah Chen",
        reviewerRole: "Product Manager",
        reviewerCompany: "Studio Digital Dreams",
        reviewerAvatar: "/sarah-chen.png",
        rating: 5,
        comment:
          "Miyazaki's work is absolutely magical. They transformed our static website into an immersive experience that our users love. Their attention to detail and creative problem-solving skills are unmatched.",
        date: "2024-01-15",
        projectWorkedOn: "Interactive Portfolio Platform",
      },
      {
        id: "t2",
        reviewerName: "David Rodriguez",
        reviewerRole: "Creative Director",
        reviewerCompany: "Anime Interactive Co.",
        reviewerAvatar: "/david-rodriguez-portrait.png",
        rating: 5,
        comment:
          "Working with Miyazaki was a dream. They understood our vision perfectly and delivered animations that exceeded our expectations. Professional, creative, and always on time.",
        date: "2023-11-22",
        projectWorkedOn: "Character Animation System",
      },
      {
        id: "t3",
        reviewerName: "Emily Watson",
        reviewerRole: "Startup Founder",
        reviewerCompany: "DreamTech Ventures",
        reviewerAvatar: "/portrait-woman-thoughtful.png",
        rating: 5,
        comment:
          "Miyazaki helped us build our MVP with beautiful animations that made our app stand out. Their code quality is excellent and they're great at explaining technical concepts to non-technical team members.",
        date: "2023-09-10",
        projectWorkedOn: "Startup MVP Development",
      },
    ],
    recentProjects: [
      {
        name: "Spirited Away Dashboard",
        description:
          "Full-stack admin dashboard with magical animations and Studio Ghibli-inspired design. Features real-time data updates and interactive charts.",
        tech: ["React", "Node.js", "TypeScript", "Framer Motion", "D3.js"],
        duration: "3 months",
        role: "Lead Developer",
        teamSize: "Solo project",
        outcome: "Increased user engagement by 150% and reduced bounce rate by 40%",
      },
      {
        name: "Totoro Weather App",
        description:
          "A charming weather application with character animations that change based on current conditions. Includes detailed forecasts and location services.",
        tech: ["Next.js", "Express", "CSS Animations", "OpenWeather API"],
        duration: "6 weeks",
        role: "Full-Stack Developer",
        teamSize: "2 developers",
        outcome: "Featured in App Store and gained 10k+ downloads in first month",
      },
      {
        name: "Kiki's Delivery Service Planner",
        description:
          "A task management app with a delightful Kiki-themed interface, helping users organize their daily deliveries and tasks.",
        tech: ["React", "Firebase", "Tailwind CSS"],
        duration: "2 months",
        role: "Frontend Developer",
        teamSize: "3 person team",
        outcome: "Improved task completion rates by 60% for beta users",
      },
    ],
    icon: Palette,
    theme: {
      cardBg: "bg-ghibli-dark/70 backdrop-blur-sm",
      border: "border-purple-500/30",
      headerBg: "bg-gradient-to-r from-purple-600 to-pink-600",
      titleText: "text-ghibli-blue",
      descText: "text-ghibli-purple",
      badgeBg: "bg-green-500/20",
      badgeText: "text-green-300",
      avatarBg: "bg-purple-500/20",
      skillBadge: "bg-ghibli-cyan/20 text-ghibli-cyan border-ghibli-cyan/30",
      projectBg: "bg-ghibli-dark/50",
      primaryButton: "bg-ghibli-blue hover:bg-ghibli-blue/90 text-ghibli-darker font-semibold",
      pattern: "bg-[radial-gradient(circle_at_50%_50%,rgba(123,104,238,0.05)_0%,transparent_60%)]",
    },
    socialLinks: {
      github: "https://github.com/miyazaki-coder",
      twitter: "https://twitter.com/ghibli_magic_dev",
      linkedin: "https://linkedin.com/in/miyazakicoder",
      website: "https://miyazaki-codes.dev",
    },
  },
  {
    id: "2",
    name: "Neon Synthwave",
    vibe: "Cyberpunk Retro",
    platform: "mobile",
    bio: "Building neon-lit mobile experiences with React Native.",
    fullBio:
      "I create full-stack mobile applications that pulse with cyberpunk energy. Specializing in React Native and modern backend technologies, I build apps that feel like they're straight out of Blade Runner. My focus is on sleek UIs, performant backends, and integrating cutting-edge features like real-time communication and AR.",
    location: "San Francisco, CA",
    timezone: "PST",
    rating: 4.8,
    reviews: 89,
    projects: 38,
    likes: 256,
    status: "Busy",
    avatar: "/images/neon_synthwave.jpeg",
    themeIcon: "🔋",
    skills: [
      "React Native",
      "Node.js",
      "TypeScript",
      "Express",
      "MongoDB",
      "Socket.io",
      "Redux",
      "Expo",
      "GraphQL",
      "Firebase",
    ],
    workExperience: [
      {
        company: "CyberTech Solutions",
        role: "Senior Mobile Developer",
        duration: "2021 - Present",
        location: "San Francisco, CA",
        description:
          "Lead mobile development for fintech applications. Built secure, high-performance React Native apps handling millions in transactions. Implemented real-time features and AR capabilities.",
        technologies: ["React Native", "Node.js", "MongoDB", "Socket.io", "AR Kit"],
        companyLogo: "/placeholder.svg?width=40&height=40",
      },
      {
        company: "NeonApps Inc.",
        role: "Mobile Developer",
        duration: "2019 - 2021",
        location: "San Francisco, CA",
        description:
          "Developed consumer mobile applications with focus on performance and user experience. Specialized in creating smooth animations and implementing complex state management.",
        technologies: ["React Native", "Redux", "Firebase", "Expo"],
        companyLogo: "/placeholder.svg?width=40&height=40",
      },
    ],
    compensation: {
      hourlyRate: "$85 - $140/hour",
      projectRate: "$8,000 - $35,000",
      availability: "25-35 hours/week",
      preferredEngagement: "Project-based",
    },
    testimonials: [
      {
        id: "t4",
        reviewerName: "Marcus Johnson",
        reviewerRole: "CTO",
        reviewerCompany: "FinanceFlow",
        reviewerAvatar: "/placeholder.svg?width=40&height=40",
        rating: 5,
        comment:
          "Neon delivered a complex fintech mobile app that handles real-time transactions flawlessly. Their expertise in React Native and backend integration is exceptional.",
        date: "2024-02-01",
        projectWorkedOn: "FinanceFlow Mobile App",
      },
      {
        id: "t5",
        reviewerName: "Lisa Park",
        reviewerRole: "Product Owner",
        reviewerCompany: "StartupX",
        reviewerAvatar: "/placeholder.svg?width=40&height=40",
        rating: 4,
        comment:
          "Great technical skills and delivered on time. The app performance is excellent and the cyberpunk aesthetic really made our product stand out in the market.",
        date: "2023-12-15",
        projectWorkedOn: "Gaming Social Platform",
      },
    ],
    recentProjects: [
      {
        name: "Cyberpunk Chat App",
        description:
          "Real-time messaging app with neon UI, custom themes, and end-to-end encryption. Supports group chats and file sharing.",
        tech: ["React Native", "Node.js", "Socket.io", "MongoDB", "Expo"],
        duration: "4 months",
        role: "Lead Mobile Developer",
        teamSize: "4 person team",
        outcome: "50k+ downloads and 4.8 App Store rating",
      },
      {
        name: "Neural Fitness Tracker",
        description:
          "AI-powered fitness tracking with cyberpunk aesthetics. Provides personalized workout plans and progress visualization.",
        tech: ["React Native", "Express", "TensorFlow.js", "SQLite"],
        duration: "5 months",
        role: "Full-Stack Developer",
        teamSize: "Solo project",
        outcome: "Featured by Apple as 'App of the Day'",
      },
    ],
    icon: Zap,
    theme: {
      cardBg: "bg-gradient-to-br from-green-900/80 to-cyan-900/80 backdrop-blur-md",
      border: "border-green-500/30",
      headerBg: "bg-gradient-to-r from-green-600 to-cyan-600",
      titleText: "text-green-300",
      descText: "text-green-200",
      badgeBg: "bg-red-500/20",
      badgeText: "text-red-300",
      avatarBg: "bg-green-500/20",
      skillBadge: "bg-green-500/20 text-green-300 border-green-500/30",
      projectBg: "bg-green-500/10",
      primaryButton: "bg-green-600 hover:bg-green-700 text-white",
      pattern: "bg-[radial-gradient(circle_at_50%_50%,rgba(34,197,94,0.1)_0%,transparent_50%)]",
    },
    socialLinks: {
      github: "https://github.com/neonsynth",
      twitter: "https://twitter.com/synthwavecoder",
      linkedin: "https://linkedin.com/in/neonsynthwave",
    },
  },
  {
    id: "3",
    name: "Luna Starweaver",
    vibe: "Celestial Mystical",
    platform: "desktop",
    bio: "Weaving cosmic magic across the entire technology stack.",
    fullBio:
      "I'm a full-stack developer who believes in the magic of seamless integration between frontend and backend. With expertise spanning from React to Node.js, I create complete digital experiences that feel otherworldly. My projects often involve complex data visualizations and interactive elements inspired by the cosmos.",
    location: "Austin, TX",
    timezone: "CST",
    rating: 4.9,
    reviews: 156,
    projects: 67,
    likes: 445,
    status: "Available",
    avatar: "/images/luna_starweaver.jpeg",
    themeIcon: "🌙",
    skills: [
      "React",
      "Node.js",
      "TypeScript",
      "MongoDB",
      "GraphQL",
      "Next.js",
      "Tailwind",
      "Prisma",
      "Three.js",
      "D3.js",
    ],
    workExperience: [
      {
        company: "Cosmic Data Corp",
        role: "Full-Stack Architect",
        duration: "2020 - Present",
        location: "Austin, TX",
        description:
          "Architect and lead developer for data visualization platforms. Design and implement complex full-stack solutions for enterprise clients. Specialize in real-time data processing and interactive visualizations.",
        technologies: ["React", "Node.js", "GraphQL", "PostgreSQL", "D3.js"],
        companyLogo: "/placeholder.svg?width=40&height=40",
      },
      {
        company: "StarTech Solutions",
        role: "Senior Developer",
        duration: "2018 - 2020",
        location: "Austin, TX",
        description:
          "Full-stack development for e-commerce and social platforms. Built scalable applications handling high traffic loads. Mentored team members and established coding standards.",
        technologies: ["React", "Express", "MongoDB", "Redis", "AWS"],
        companyLogo: "/placeholder.svg?width=40&height=40",
      },
    ],
    compensation: {
      hourlyRate: "$90 - $150/hour",
      projectRate: "$10,000 - $50,000",
      availability: "35-45 hours/week",
      preferredEngagement: "Both",
    },
    testimonials: [
      {
        id: "t6",
        reviewerName: "Alex Thompson",
        reviewerRole: "VP Engineering",
        reviewerCompany: "DataViz Pro",
        reviewerAvatar: "/placeholder.svg?width=40&height=40",
        rating: 5,
        comment:
          "Luna's ability to create beautiful, interactive data visualizations is unmatched. They delivered a complex dashboard that our clients absolutely love. Highly recommended!",
        date: "2024-01-20",
        projectWorkedOn: "Enterprise Analytics Dashboard",
      },
    ],
    recentProjects: [
      {
        name: "Celestial E-commerce",
        description:
          "Full-stack e-commerce platform with real-time inventory updates, secure payments, and a cosmic-themed user interface.",
        tech: ["Next.js", "Node.js", "MongoDB", "GraphQL", "Stripe"],
        duration: "6 months",
        role: "Full-Stack Architect",
        teamSize: "5 person team",
        outcome: "Increased conversion rate by 85% and reduced cart abandonment by 50%",
      },
      {
        name: "Moonlight Social",
        description:
          "A social media platform with advanced real-time messaging, content sharing, and mystical themes. Features include astrological insights and event planning.",
        tech: ["React", "Express", "GraphQL", "PostgreSQL", "WebSockets"],
        duration: "8 months",
        role: "Lead Developer",
        teamSize: "6 person team",
        outcome: "Gained 25k+ active users within 3 months of launch",
      },
    ],
    icon: Sparkles,
    theme: {
      cardBg: "bg-gradient-to-br from-indigo-900/80 to-purple-900/80 backdrop-blur-md",
      border: "border-indigo-500/30",
      headerBg: "bg-gradient-to-r from-indigo-600 to-purple-600",
      titleText: "text-indigo-300",
      descText: "text-indigo-200",
      badgeBg: "bg-green-500/20",
      badgeText: "text-green-300",
      avatarBg: "bg-indigo-500/20",
      skillBadge: "bg-indigo-500/20 text-indigo-300 border-indigo-500/30",
      projectBg: "bg-indigo-500/10",
      primaryButton: "bg-indigo-600 hover:bg-indigo-700 text-white",
      pattern: "bg-[radial-gradient(circle_at_50%_50%,rgba(99,102,241,0.1)_0%,transparent_50%)]",
    },
    socialLinks: {
      github: "https://github.com/lunastar",
      linkedin: "https://linkedin.com/in/lunastarweaver",
      website: "https://luna-codes.space",
    },
  },
  {
    id: "4",
    name: "Retro Phoenix",
    vibe: "80s Arcade Nostalgia",
    platform: "mobile",
    bio: "Crafting pixel-perfect mobile experiences with retro flair.",
    fullBio:
      "I bring the nostalgia of 80s arcade games to modern mobile development. Specializing in React Native and full-stack development, I create apps that are both functional and fun, with a heavy dose of retro aesthetics. My work emphasizes responsive design and engaging gameplay mechanics.",
    location: "Berlin, Germany",
    timezone: "CET",
    rating: 4.7,
    reviews: 73,
    projects: 29,
    likes: 189,
    status: "Available",
    avatar: "/images/retro_phoenix.jpeg",
    themeIcon: "🕹️",
    skills: [
      "React Native",
      "Node.js",
      "Express",
      "Firebase",
      "Redux",
      "Expo",
      "TypeScript",
      "Socket.io",
      "Pixel Art",
      "Game Design",
    ],
    workExperience: [
      {
        company: "RetroGames Studio",
        role: "Mobile Game Developer",
        duration: "2021 - Present",
        location: "Berlin, Germany",
        description:
          "Lead mobile game development with focus on retro aesthetics and modern performance. Created multiple successful indie games with pixel art styling and engaging gameplay mechanics.",
        technologies: ["React Native", "Unity", "Firebase", "Redux"],
        companyLogo: "/placeholder.svg?width=40&height=40",
      },
    ],
    compensation: {
      hourlyRate: "$65 - $100/hour",
      projectRate: "$4,000 - $20,000",
      availability: "20-30 hours/week",
      preferredEngagement: "Project-based",
    },
    testimonials: [
      {
        id: "t7",
        reviewerName: "Sophie Mueller",
        reviewerRole: "Game Producer",
        reviewerCompany: "Indie Games Co.",
        reviewerAvatar: "/placeholder.svg?width=40&height=40",
        rating: 5,
        comment:
          "Phoenix created an amazing retro-style mobile game for us. The pixel art and gameplay mechanics are perfectly balanced. Great communication throughout the project.",
        date: "2023-10-05",
        projectWorkedOn: "Neon Runner Game",
      },
    ],
    recentProjects: [
      {
        name: "Pixel Quest RPG",
        description:
          "A retro-style mobile RPG with a modern full-stack architecture, featuring turn-based combat and a branching narrative.",
        tech: ["React Native", "Node.js", "Redux", "Firebase", "Aseprite"],
        duration: "7 months",
        role: "Lead Developer",
        teamSize: "3 person team",
        outcome: "100k+ downloads and featured in Google Play Indie Corner",
      },
      {
        name: "Neon Fitness Tracker",
        description:
          "An 80s-inspired fitness tracking app with real-time sync, customizable workout routines, and vibrant neon visuals.",
        tech: ["React Native", "Express", "SQLite", "Charts.js"],
        duration: "3 months",
        role: "Solo Developer",
        teamSize: "Solo project",
        outcome: "4.6 star rating and 25k+ active users",
      },
    ],
    icon: Gamepad2,
    theme: {
      cardBg: "bg-gradient-to-br from-pink-900/80 to-orange-900/80 backdrop-blur-md",
      border: "border-pink-500/30",
      headerBg: "bg-gradient-to-r from-pink-600 to-orange-600",
      titleText: "text-pink-400",
      descText: "text-orange-400",
      badgeBg: "bg-green-500/20",
      badgeText: "text-green-300",
      avatarBg: "bg-pink-500/20",
      skillBadge: "bg-pink-500/20 text-pink-400 border-pink-500/30",
      projectBg: "bg-pink-500/10",
      primaryButton: "bg-pink-600 hover:bg-pink-700 text-white",
      pattern: "bg-[radial-gradient(circle_at_50%_50%,rgba(236,72,153,0.1)_0%,transparent_50%)]",
    },
    socialLinks: {
      github: "https://github.com/retrogamerdev",
      twitter: "https://twitter.com/8bitphoenix",
    },
  },
  {
    id: "5",
    name: "Ocean Dreamer",
    vibe: "Aquatic Serenity",
    platform: "desktop",
    bio: "Creating fluid, wave-like user experiences.",
    fullBio:
      "I'm inspired by the ocean's endless depths and create full-stack applications that flow like water. With expertise in modern web technologies, I build serene, calming digital experiences that wash over users like gentle waves. My focus is on smooth animations, intuitive navigation, and data visualization that tells a story.",
    location: "Seattle, WA",
    timezone: "PST",
    rating: 4.9,
    reviews: 94,
    projects: 31,
    likes: 312,
    status: "Available",
    avatar: "",
    themeIcon: "🌊",
    skills: [
      "React",
      "Next.js",
      "Node.js",
      "TypeScript",
      "Prisma",
      "PostgreSQL",
      "Framer Motion",
      "Three.js",
      "D3.js",
      "WebGL",
    ],
    workExperience: [
      {
        company: "AquaTech Innovations",
        role: "Senior Frontend Developer",
        duration: "2020 - Present",
        location: "Seattle, WA",
        description:
          "Lead frontend development for ocean research and marine biology applications. Create immersive data visualizations and interactive experiences for scientific research platforms.",
        technologies: ["React", "Three.js", "D3.js", "WebGL", "TypeScript"],
        companyLogo: "/placeholder.svg?width=40&height=40",
      },
    ],
    compensation: {
      hourlyRate: "$80 - $125/hour",
      projectRate: "$6,000 - $30,000",
      availability: "30-40 hours/week",
      preferredEngagement: "Both",
    },
    testimonials: [
      {
        id: "t8",
        reviewerName: "Dr. Marina Santos",
        reviewerRole: "Research Director",
        reviewerCompany: "Ocean Research Institute",
        reviewerAvatar: "/placeholder.svg?width=40&height=40",
        rating: 5,
        comment:
          "Ocean's work on our marine data visualization platform is extraordinary. They made complex oceanographic data accessible and beautiful. Truly talented developer.",
        date: "2023-11-30",
        projectWorkedOn: "Marine Data Platform",
      },
    ],
    recentProjects: [
      {
        name: "Tidal Music Platform",
        description:
          "A full-stack music streaming platform with fluid, wave-like animations, personalized playlists, and high-fidelity audio support.",
        tech: ["Next.js", "Node.js", "PostgreSQL", "Framer Motion", "Web Audio API"],
        duration: "5 months",
        role: "Full-Stack Developer",
        teamSize: "4 person team",
        outcome: "Launched with 15k+ subscribers in first month",
      },
      {
        name: "Wave Analytics Dashboard",
        description:
          "An interactive data visualization platform with an ocean-inspired design, helping users explore complex datasets through intuitive charts and graphs.",
        tech: ["React", "Express", "D3.js", "MongoDB"],
        duration: "4 months",
        role: "Frontend Lead",
        teamSize: "3 person team",
        outcome: "Improved data analysis efficiency by 200% for client teams",
      },
    ],
    icon: Waves,
    theme: {
      cardBg: "bg-gradient-to-br from-blue-900/80 to-cyan-900/80 backdrop-blur-md",
      border: "border-blue-500/30",
      headerBg: "bg-gradient-to-r from-blue-600 to-cyan-600",
      titleText: "text-blue-300",
      descText: "text-cyan-300",
      badgeBg: "bg-green-500/20",
      badgeText: "text-green-300",
      avatarBg: "bg-blue-500/20",
      skillBadge: "bg-blue-500/20 text-blue-300 border-blue-500/30",
      projectBg: "bg-blue-500/10",
      primaryButton: "bg-blue-600 hover:bg-blue-700 text-white",
      pattern: "bg-[radial-gradient(circle_at_50%_50%,rgba(59,130,246,0.1)_0%,transparent_50%)]",
    },
    socialLinks: {
      github: "https://github.com/oceancodes",
      linkedin: "https://linkedin.com/in/oceandreamer",
      website: "https://oceandreamer.dev",
    },
  },
  {
    id: "6",
    name: "Forest Sage",
    vibe: "Natural Earthy",
    platform: "mobile",
    bio: "Growing organic mobile experiences from the ground up.",
    fullBio:
      "I believe in sustainable, organic code that grows naturally. Specializing in React Native and eco-friendly development practices, I create mobile applications that feel as natural as a walk through the forest. My apps often incorporate location-based services and community features.",
    location: "Portland, OR",
    timezone: "PST",
    rating: 4.8,
    reviews: 67,
    projects: 45,
    likes: 234,
    status: "Available",
    avatar: "/images/forest_sage.jpeg",
    themeIcon: "🌲",
    skills: [
      "React Native",
      "Node.js",
      "Express",
      "MongoDB",
      "TypeScript",
      "Expo",
      "GraphQL",
      "Firebase",
      "Mapbox GL JS",
      "SQLite",
    ],
    workExperience: [
      {
        company: "EcoTech Solutions",
        role: "Mobile Developer",
        duration: "2019 - Present",
        location: "Portland, OR",
        description:
          "Develop mobile applications focused on environmental sustainability and community engagement. Specialize in location-based services and offline-first architecture.",
        technologies: ["React Native", "Node.js", "MongoDB", "Mapbox"],
        companyLogo: "/placeholder.svg?width=40&height=40",
      },
    ],
    compensation: {
      hourlyRate: "$70 - $110/hour",
      projectRate: "$5,000 - $25,000",
      availability: "25-35 hours/week",
      preferredEngagement: "Project-based",
    },
    testimonials: [
      {
        id: "t9",
        reviewerName: "Green Initiative Team",
        reviewerRole: "Project Manager",
        reviewerCompany: "EcoApps Collective",
        reviewerAvatar: "/placeholder.svg?width=40&height=40",
        rating: 5,
        comment:
          "Forest created a beautiful sustainability tracking app that perfectly captures our environmental mission. Clean code, great UX, and delivered on time.",
        date: "2023-09-15",
        projectWorkedOn: "EcoTracker Mobile",
      },
    ],
    recentProjects: [
      {
        name: "EcoTracker Mobile",
        description:
          "A sustainability tracking app with natural design patterns, helping users monitor their environmental impact and discover eco-friendly alternatives.",
        tech: ["React Native", "Node.js", "MongoDB", "GraphQL", "Expo"],
        duration: "4 months",
        role: "Lead Developer",
        teamSize: "2 person team",
        outcome: "30k+ downloads and 4.7 star rating",
      },
      {
        name: "Forest Meditation App",
        description:
          "A mindfulness app featuring guided meditations, nature sounds, and an organic user interface designed to promote relaxation and connection with nature.",
        tech: ["React Native", "Express", "Firebase", "Audio APIs"],
        duration: "3 months",
        role: "Solo Developer",
        teamSize: "Solo project",
        outcome: "Featured in wellness app collections and 20k+ active users",
      },
    ],
    icon: TreePine,
    theme: {
      cardBg: "bg-gradient-to-br from-green-900/80 to-emerald-900/80 backdrop-blur-md",
      border: "border-green-600/30",
      headerBg: "bg-gradient-to-r from-green-700 to-emerald-600",
      titleText: "text-green-400",
      descText: "text-emerald-400",
      badgeBg: "bg-yellow-500/20",
      badgeText: "text-yellow-300",
      avatarBg: "bg-green-600/20",
      skillBadge: "bg-green-600/20 text-green-400 border-green-600/30",
      projectBg: "bg-green-600/10",
      primaryButton: "bg-green-700 hover:bg-green-800 text-white",
      pattern: "bg-[radial-gradient(circle_at_50%_50%,rgba(34,197,94,0.1)_0%,transparent_50%)]",
    },
    socialLinks: {
      github: "https://github.com/forestdev",
      twitter: "https://twitter.com/forestsagecodes",
    },
  },
  {
    id: "7",
    name: "Café Minimalist",
    vibe: "Cozy Coffee Shop",
    platform: "desktop",
    bio: "Brewing simple, elegant full-stack solutions.",
    fullBio:
      "I believe in the power of simplicity and warmth in design. Like a perfectly crafted cup of coffee, I create full-stack applications that are both comforting and energizing, with clean code and intuitive interfaces. My expertise lies in e-commerce and content management systems.",
    location: "Copenhagen, Denmark",
    timezone: "CET",
    rating: 4.9,
    reviews: 112,
    projects: 53,
    likes: 387,
    status: "Available",
    avatar: "/images/cafe_minimalist.jpeg",
    themeIcon: "☕",
    skills: [
      "React",
      "Next.js",
      "Node.js",
      "TypeScript",
      "Prisma",
      "PostgreSQL",
      "Tailwind CSS",
      "Vercel",
      "Shopify API",
      "Stripe",
    ],
    workExperience: [
      {
        company: "Nordic Design Co.",
        role: "Full-Stack Developer",
        duration: "2020 - Present",
        location: "Copenhagen, Denmark",
        description:
          "Create minimalist e-commerce and content management solutions for Scandinavian design companies. Focus on clean, accessible interfaces and sustainable development practices.",
        technologies: ["Next.js", "Prisma", "PostgreSQL", "Tailwind CSS"],
        companyLogo: "/placeholder.svg?width=40&height=40",
      },
    ],
    compensation: {
      hourlyRate: "$75 - $120/hour",
      projectRate: "$6,000 - $35,000",
      availability: "35-45 hours/week",
      preferredEngagement: "Both",
    },
    testimonials: [
      {
        id: "t10",
        reviewerName: "Lars Andersen",
        reviewerRole: "Store Owner",
        reviewerCompany: "Copenhagen Coffee Co.",
        reviewerAvatar: "/placeholder.svg?width=40&height=40",
        rating: 5,
        comment:
          "Café built us a beautiful, minimalist e-commerce site that perfectly represents our brand. Sales increased by 40% after launch. Excellent work!",
        date: "2023-12-01",
        projectWorkedOn: "Coffee Shop E-commerce",
      },
    ],
    recentProjects: [
      {
        name: "Brew Journal",
        description:
          "A coffee tracking and discovery app with a minimalist design, allowing users to log their brews, share reviews, and find new roasters.",
        tech: ["Next.js", "Prisma", "PostgreSQL", "Tailwind CSS", "Vercel"],
        duration: "3 months",
        role: "Full-Stack Developer",
        teamSize: "Solo project",
        outcome: "Featured in coffee community blogs and 5k+ active users",
      },
      {
        name: "Cozy Bookstore",
        description:
          "An e-commerce platform for independent bookstores, featuring inventory management, secure payments, and a warm, inviting user experience.",
        tech: ["React", "Node.js", "Express", "MongoDB", "Stripe"],
        duration: "5 months",
        role: "Lead Developer",
        teamSize: "3 person team",
        outcome: "Helped 12 independent bookstores increase online sales by 60%",
      },
    ],
    icon: Coffee,
    theme: {
      cardBg: "bg-gradient-to-br from-amber-900/80 to-orange-900/80 backdrop-blur-md",
      border: "border-amber-500/30",
      headerBg: "bg-gradient-to-r from-amber-600 to-orange-600",
      titleText: "text-amber-400",
      descText: "text-orange-400",
      badgeBg: "bg-green-500/20",
      badgeText: "text-green-300",
      avatarBg: "bg-amber-500/20",
      skillBadge: "bg-amber-500/20 text-amber-400 border-amber-500/30",
      projectBg: "bg-amber-500/10",
      primaryButton: "bg-amber-600 hover:bg-amber-700 text-white",
      pattern: "bg-[radial-gradient(circle_at_50%_50%,rgba(245,158,11,0.1)_0%,transparent_50%)]",
    },
    socialLinks: {
      github: "https://github.com/minimalcoder",
      linkedin: "https://linkedin.com/in/cafeminimalist",
      website: "https://cafecodes.com",
    },
  },
  // NEW CODERS ADDED BELOW
  {
    id: "8",
    name: "Quantum Coder",
    vibe: "Futuristic Scientific",
    platform: "desktop",
    bio: "Bridging quantum computing concepts with modern web development.",
    fullBio:
      "With a background in quantum physics and computer science, I create applications that bring complex scientific concepts to life through intuitive interfaces. I specialize in data visualization for scientific applications, simulation tools, and educational platforms that make cutting-edge concepts accessible to everyone.",
    location: "Zurich, Switzerland",
    timezone: "CET",
    rating: 4.9,
    reviews: 78,
    projects: 34,
    likes: 267,
    status: "Available",
    avatar: "",
    themeIcon: "⚛️",
    skills: [
      "React",
      "TypeScript",
      "Python",
      "D3.js",
      "WebGL",
      "Three.js",
      "TensorFlow.js",
      "Node.js",
      "Scientific Computing",
      "Data Visualization",
    ],
    workExperience: [
      {
        company: "Quantum Solutions",
        role: "Lead Frontend Developer",
        duration: "2021 - Present",
        location: "Zurich, Switzerland",
        description:
          "Develop interactive visualizations and simulations for quantum computing concepts. Create educational tools and dashboards for researchers and students in quantum physics.",
        technologies: ["React", "TypeScript", "D3.js", "WebGL", "Python"],
        companyLogo: "/quantum-solutions-logo.png",
      },
      {
        company: "Quantum Research Institute",
        role: "Scientific Visualization Specialist",
        duration: "2019 - 2021",
        location: "Zurich, Switzerland",
        description:
          "Created interactive visualizations for quantum physics research. Developed web-based tools for data analysis and simulation of quantum systems.",
        technologies: ["JavaScript", "D3.js", "Python", "WebGL", "GLSL"],
        companyLogo: "/quantum-research-institute-logo.png",
      },
    ],
    compensation: {
      hourlyRate: "$95 - $160/hour",
      projectRate: "$10,000 - $45,000",
      availability: "25-35 hours/week",
      preferredEngagement: "Both",
    },
    testimonials: [
      {
        id: "t11",
        reviewerName: "Dr. Elena Petrova",
        reviewerRole: "Research Director",
        reviewerCompany: "Quantum Research Institute",
        reviewerAvatar: "/elena-petrova.png",
        rating: 5,
        comment:
          "Quantum Coder transformed our complex research data into beautiful, interactive visualizations that have significantly improved how we communicate our findings. Their deep understanding of both quantum concepts and modern web technologies is truly unique.",
        date: "2024-01-10",
        projectWorkedOn: "Quantum Simulation Platform",
      },
    ],
    recentProjects: [
      {
        name: "Quantum Finance Simulator",
        description:
          "An educational platform that visualizes quantum algorithms for financial modeling, with interactive simulations and real-time data processing.",
        tech: ["React", "TypeScript", "D3.js", "WebGL", "Python", "TensorFlow.js"],
        duration: "6 months",
        role: "Lead Developer",
        teamSize: "4 person team",
        outcome: "Adopted by 3 major universities for quantum computing courses",
      },
      {
        name: "Quantum Playground",
        description:
          "An interactive web application that allows users to experiment with quantum computing concepts through visual programming and real-time simulations.",
        tech: ["React", "Three.js", "Node.js", "WebAssembly", "GLSL"],
        duration: "4 months",
        role: "Full-Stack Developer",
        teamSize: "2 person team",
        outcome: "Featured in Scientific American and reached 50k+ users",
      },
    ],
    icon: Cpu,
    theme: {
      cardBg: "bg-gradient-to-br from-slate-900/80 to-violet-900/80 backdrop-blur-md",
      border: "border-violet-500/30",
      headerBg: "bg-gradient-to-r from-slate-700 to-violet-700",
      titleText: "text-violet-300",
      descText: "text-slate-300",
      badgeBg: "bg-blue-500/20",
      badgeText: "text-blue-300",
      avatarBg: "bg-violet-500/20",
      skillBadge: "bg-violet-500/20 text-violet-300 border-violet-500/30",
      projectBg: "bg-violet-500/10",
      primaryButton: "bg-violet-600 hover:bg-violet-700 text-white",
      pattern: "bg-[radial-gradient(circle_at_50%_50%,rgba(139,92,246,0.1)_0%,transparent_50%)]",
    },
    socialLinks: {
      github: "https://github.com/quantumcoder",
      twitter: "https://twitter.com/quantum_dev",
      linkedin: "https://linkedin.com/in/quantumcoder",
      website: "https://quantum-visualizations.dev",
    },
  },
  {
    id: "9",
    name: "Eco Tech Developer",
    vibe: "Sustainable Technology",
    platform: "desktop",
    bio: "Creating eco-conscious digital solutions for a sustainable future.",
    fullBio:
      "I'm passionate about using technology to address environmental challenges. With expertise in sustainable web development practices, I create energy-efficient applications that minimize carbon footprint while maximizing performance. My work focuses on green tech solutions, environmental monitoring platforms, and tools that promote sustainability.",
    location: "Vancouver, Canada",
    timezone: "PST",
    rating: 4.8,
    reviews: 91,
    projects: 37,
    likes: 278,
    status: "Available",
    avatar: "",
    themeIcon: "🌱",
    skills: [
      "React",
      "Next.js",
      "Node.js",
      "TypeScript",
      "Sustainable Web Design",
      "Green Hosting",
      "IoT",
      "Data Visualization",
      "PostgreSQL",
      "Mapbox",
    ],
    workExperience: [
      {
        company: "GreenCode Technologies",
        role: "Senior Sustainability Developer",
        duration: "2020 - Present",
        location: "Vancouver, Canada",
        description:
          "Lead development of eco-friendly web applications with minimal environmental impact. Implement energy-efficient code practices and optimize applications for reduced carbon footprint.",
        technologies: ["React", "Next.js", "Node.js", "Green Web Hosting", "Performance Optimization"],
        companyLogo: "/greencode-logo.png",
      },
      {
        company: "GreenShop Collective",
        role: "Full-Stack Developer",
        duration: "2018 - 2020",
        location: "Vancouver, Canada",
        description:
          "Developed e-commerce platforms for sustainable products with focus on energy efficiency and performance. Created tools for carbon footprint tracking and environmental impact assessment.",
        technologies: ["React", "Express", "MongoDB", "PWA", "Sustainable UX"],
        companyLogo: "/greenshop-collective-logo.png",
      },
    ],
    compensation: {
      hourlyRate: "$80 - $130/hour",
      projectRate: "$7,000 - $30,000",
      availability: "30-40 hours/week",
      preferredEngagement: "Both",
    },
    testimonials: [
      {
        id: "t12",
        reviewerName: "Michael Chen",
        reviewerRole: "Sustainability Director",
        reviewerCompany: "EcoFuture Initiative",
        reviewerAvatar: "/michael-chen.png",
        rating: 5,
        comment:
          "Eco Tech Developer created an incredible platform for our environmental monitoring project. Not only is the application beautiful and functional, but they also ensured it was optimized for minimal energy consumption. Their commitment to sustainable development practices is truly impressive.",
        date: "2023-11-15",
        projectWorkedOn: "Carbon Footprint Tracker",
      },
    ],
    recentProjects: [
      {
        name: "Carbon Footprint Tracker",
        description:
          "A comprehensive platform for individuals and businesses to track, analyze, and reduce their carbon footprint with personalized recommendations.",
        tech: ["Next.js", "TypeScript", "PostgreSQL", "D3.js", "PWA", "Sustainable Web Design"],
        duration: "5 months",
        role: "Lead Developer",
        teamSize: "3 person team",
        outcome: "Helped users reduce carbon emissions by an average of 15%",
      },
      {
        name: "Green Energy Dashboard",
        description:
          "An energy monitoring system for smart homes that visualizes consumption patterns and provides AI-powered recommendations for reducing energy usage.",
        tech: ["React", "Node.js", "IoT Integration", "TensorFlow.js", "Time-series DB"],
        duration: "4 months",
        role: "Full-Stack Developer",
        teamSize: "2 person team",
        outcome: "Reduced energy consumption by 20% for participating households",
      },
    ],
    icon: Leaf,
    theme: {
      cardBg: "bg-gradient-to-br from-emerald-900/80 to-teal-900/80 backdrop-blur-md",
      border: "border-emerald-500/30",
      headerBg: "bg-gradient-to-r from-emerald-700 to-teal-700",
      titleText: "text-emerald-300",
      descText: "text-teal-300",
      badgeBg: "bg-yellow-500/20",
      badgeText: "text-yellow-300",
      avatarBg: "bg-emerald-500/20",
      skillBadge: "bg-emerald-500/20 text-emerald-300 border-emerald-500/30",
      projectBg: "bg-emerald-500/10",
      primaryButton: "bg-emerald-600 hover:bg-emerald-700 text-white",
      pattern: "bg-[radial-gradient(circle_at_50%_50%,rgba(16,185,129,0.1)_0%,transparent_50%)]",
    },
    socialLinks: {
      github: "https://github.com/ecotechdev",
      twitter: "https://twitter.com/sustainable_dev",
      linkedin: "https://linkedin.com/in/ecotechdev",
      website: "https://sustainable-web.dev",
    },
  },
  {
    id: "10",
    name: "Accessibility Advocate",
    vibe: "Inclusive Design",
    platform: "desktop",
    bio: "Creating digital experiences that work for everyone, without exception.",
    fullBio:
      "I'm dedicated to making the web accessible to all users, regardless of ability or disability. With deep expertise in WCAG standards, assistive technologies, and inclusive design principles, I create applications that provide equal access and opportunity. My work focuses on ensuring digital experiences are usable by everyone while maintaining beautiful, engaging interfaces.",
    location: "Toronto, Canada",
    timezone: "EST",
    rating: 4.9,
    reviews: 103,
    projects: 41,
    likes: 312,
    status: "Available",
    avatar: "",
    themeIcon: "♿",
    skills: [
      "React",
      "WCAG 2.1 AA/AAA",
      "Semantic HTML",
      "ARIA",
      "Screen Reader Optimization",
      "Keyboard Navigation",
      "Color Contrast",
      "Inclusive Design",
      "User Testing",
      "TypeScript",
    ],
    workExperience: [
      {
        company: "Inclusive Digital",
        role: "Lead Accessibility Engineer",
        duration: "2019 - Present",
        location: "Toronto, Canada",
        description:
          "Lead accessibility initiatives for enterprise clients. Conduct audits, implement remediation strategies, and develop accessible components and patterns. Train development teams on accessibility best practices.",
        technologies: ["React", "WCAG 2.1", "ARIA", "Semantic HTML", "Automated Testing"],
        companyLogo: "/inclusive-digital-logo.png",
      },
      {
        company: "Digital Inclusion Foundation",
        role: "Accessibility Consultant",
        duration: "2017 - 2019",
        location: "Toronto, Canada",
        description:
          "Provided accessibility consulting for government and non-profit organizations. Conducted user testing with people with disabilities and developed accessible web solutions.",
        technologies: ["HTML", "CSS", "JavaScript", "WCAG", "Assistive Technologies"],
        companyLogo: "/digital-inclusion-foundation-logo.png",
      },
    ],
    compensation: {
      hourlyRate: "$85 - $140/hour",
      projectRate: "$8,000 - $40,000",
      availability: "30-40 hours/week",
      preferredEngagement: "Both",
    },
    testimonials: [
      {
        id: "t13",
        reviewerName: "Jessica Wong",
        reviewerRole: "Director of Digital Services",
        reviewerCompany: "Government Digital Service",
        reviewerAvatar: "/jessica-wong.png",
        rating: 5,
        comment:
          "Accessibility Advocate transformed our digital services to be truly inclusive. Their deep knowledge of accessibility standards and creative problem-solving skills helped us achieve WCAG 2.1 AA compliance while enhancing the user experience for everyone. They're passionate, thorough, and a true advocate for all users.",
        date: "2023-10-20",
        projectWorkedOn: "Government Services Portal",
      },
    ],
    recentProjects: [
      {
        name: "Accessible Learning Platform",
        description:
          "A fully accessible e-learning platform with multiple accommodation features, ensuring educational content is available to all students regardless of ability.",
        tech: ["React", "ARIA", "Semantic HTML", "Speech Recognition", "Screen Reader Optimization"],
        duration: "7 months",
        role: "Accessibility Lead",
        teamSize: "5 person team",
        outcome: "Achieved WCAG 2.1 AAA compliance and increased student engagement by 35%",
      },
      {
        name: "Inclusive Banking Portal",
        description:
          "A banking interface redesigned for maximum accessibility, featuring multiple interaction methods, clear navigation, and support for various assistive technologies.",
        tech: ["React", "TypeScript", "ARIA", "Keyboard Navigation", "High Contrast Modes"],
        duration: "6 months",
        role: "Lead Developer",
        teamSize: "4 person team",
        outcome: "Improved customer satisfaction scores by 40% among users with disabilities",
      },
    ],
    icon: Accessibility,
    theme: {
      cardBg: "bg-gradient-to-br from-blue-900/80 to-purple-900/80 backdrop-blur-md",
      border: "border-blue-500/30",
      headerBg: "bg-gradient-to-r from-blue-700 to-purple-700",
      titleText: "text-blue-300",
      descText: "text-purple-300",
      badgeBg: "bg-green-500/20",
      badgeText: "text-green-300",
      avatarBg: "bg-blue-500/20",
      skillBadge: "bg-blue-500/20 text-blue-300 border-blue-500/30",
      projectBg: "bg-blue-500/10",
      primaryButton: "bg-blue-600 hover:bg-blue-700 text-white",
      pattern: "bg-[radial-gradient(circle_at_50%_50%,rgba(59,130,246,0.1)_0%,transparent_50%)]",
    },
    socialLinks: {
      github: "https://github.com/a11yadvocate",
      twitter: "https://twitter.com/inclusive_dev",
      linkedin: "https://linkedin.com/in/accessibilityadvocate",
      website: "https://inclusive-interfaces.dev",
    },
  },
  {
    id: "11",
    name: "AI Whisperer",
    vibe: "Neural Network Mystic",
    platform: "desktop",
    bio: "Channeling the power of artificial intelligence into intuitive applications.",
    fullBio:
      "I specialize in creating AI-powered applications that feel magical yet practical. With deep expertise in machine learning, natural language processing, and computer vision, I build intelligent systems that understand and adapt to user needs. My work bridges the gap between complex AI algorithms and user-friendly interfaces.",
    location: "Montreal, Canada",
    timezone: "EST",
    rating: 4.9,
    reviews: 85,
    projects: 28,
    likes: 298,
    status: "Available",
    avatar: "",
    themeIcon: "🧠",
    skills: [
      "Machine Learning",
      "TensorFlow",
      "PyTorch",
      "Natural Language Processing",
      "Computer Vision",
      "React",
      "Python",
      "FastAPI",
      "OpenAI API",
      "Hugging Face",
    ],
    workExperience: [
      {
        company: "Neural Dynamics",
        role: "Senior AI Engineer",
        duration: "2021 - Present",
        location: "Montreal, Canada",
        description:
          "Lead development of AI-powered applications for enterprise clients. Design and implement machine learning pipelines, create intelligent user interfaces, and optimize model performance for production environments.",
        technologies: ["Python", "TensorFlow", "React", "FastAPI", "Docker"],
        companyLogo: "/neural-dynamics-logo.png",
      },
      {
        company: "AI Research Lab",
        role: "Machine Learning Developer",
        duration: "2019 - 2021",
        location: "Montreal, Canada",
        description:
          "Developed cutting-edge AI models for research projects. Specialized in computer vision and natural language processing applications. Published research papers on novel AI architectures.",
        technologies: ["PyTorch", "OpenCV", "NLTK", "Jupyter", "AWS"],
        companyLogo: "/ai-research-lab-logo.png",
      },
    ],
    compensation: {
      hourlyRate: "$100 - $180/hour",
      projectRate: "$12,000 - $50,000",
      availability: "25-35 hours/week",
      preferredEngagement: "Both",
    },
    testimonials: [
      {
        id: "t14",
        reviewerName: "Dr. Amanda Foster",
        reviewerRole: "CTO",
        reviewerCompany: "IntelliCorp",
        reviewerAvatar: "/amanda-foster.png",
        rating: 5,
        comment:
          "AI Whisperer delivered an incredible intelligent document processing system that exceeded our expectations. Their ability to make complex AI concepts accessible through elegant interfaces is remarkable. The system has improved our efficiency by 300%.",
        date: "2024-01-05",
        projectWorkedOn: "Intelligent Document Processor",
      },
    ],
    recentProjects: [
      {
        name: "Smart Content Generator",
        description:
          "An AI-powered content creation platform that generates high-quality articles, social media posts, and marketing copy using advanced language models.",
        tech: ["React", "Python", "OpenAI API", "FastAPI", "PostgreSQL", "Redis"],
        duration: "5 months",
        role: "AI Lead Developer",
        teamSize: "3 person team",
        outcome: "Generated over 1M pieces of content with 95% user satisfaction",
      },
      {
        name: "Visual Recognition Dashboard",
        description:
          "A computer vision platform that analyzes images and videos in real-time, providing insights for retail analytics and security applications.",
        tech: ["Python", "TensorFlow", "OpenCV", "React", "WebRTC", "Docker"],
        duration: "6 months",
        role: "Full-Stack AI Developer",
        teamSize: "4 person team",
        outcome: "Achieved 98% accuracy in object detection and classification",
      },
    ],
    icon: Brain,
    theme: {
      cardBg: "bg-gradient-to-br from-purple-900/80 to-pink-900/80 backdrop-blur-md",
      border: "border-purple-500/30",
      headerBg: "bg-gradient-to-r from-purple-700 to-pink-700",
      titleText: "text-purple-300",
      descText: "text-pink-300",
      badgeBg: "bg-green-500/20",
      badgeText: "text-green-300",
      avatarBg: "bg-purple-500/20",
      skillBadge: "bg-purple-500/20 text-purple-300 border-purple-500/30",
      projectBg: "bg-purple-500/10",
      primaryButton: "bg-purple-600 hover:bg-purple-700 text-white",
      pattern: "bg-[radial-gradient(circle_at_50%_50%,rgba(147,51,234,0.1)_0%,transparent_50%)]",
    },
    socialLinks: {
      github: "https://github.com/aiwhisperer",
      twitter: "https://twitter.com/neural_mystic",
      linkedin: "https://linkedin.com/in/aiwhisperer",
      website: "https://neural-interfaces.ai",
    },
  },
  {
    id: "12",
    name: "Sound Architect",
    vibe: "Audio-Visual Harmony",
    platform: "desktop",
    bio: "Crafting immersive audio experiences through code and creativity.",
    fullBio:
      "I specialize in creating applications that blend audio engineering with cutting-edge web technologies. From music production tools to interactive sound installations, I build platforms that let users create, manipulate, and experience audio in new ways. My work combines deep technical knowledge of audio processing with intuitive user interface design.",
    location: "Nashville, TN",
    timezone: "CST",
    rating: 4.8,
    reviews: 72,
    projects: 26,
    likes: 189,
    status: "Available",
    avatar: "",
    themeIcon: "🎵",
    skills: [
      "Web Audio API",
      "React",
      "TypeScript",
      "Audio Processing",
      "WebRTC",
      "Node.js",
      "Digital Signal Processing",
      "Music Theory",
      "Three.js",
      "WebGL",
    ],
    workExperience: [
      {
        company: "Sonic Innovations",
        role: "Lead Audio Developer",
        duration: "2020 - Present",
        location: "Nashville, TN",
        description:
          "Develop web-based audio applications and music production tools. Create real-time audio processing systems and interactive sound experiences for artists and producers.",
        technologies: ["Web Audio API", "React", "WebRTC", "Node.js", "TypeScript"],
        companyLogo: "/sonic-innovations-logo.png",
      },
      {
        company: "Digital Music Studio",
        role: "Audio Software Developer",
        duration: "2018 - 2020",
        location: "Nashville, TN",
        description:
          "Built custom audio plugins and web applications for music production. Specialized in real-time audio effects and collaborative music creation platforms.",
        technologies: ["JavaScript", "Web Audio API", "C++", "JUCE", "WebAssembly"],
        companyLogo: "/digital-music-studio-logo.png",
      },
    ],
    compensation: {
      hourlyRate: "$85 - $145/hour",
      projectRate: "$8,000 - $35,000",
      availability: "30-40 hours/week",
      preferredEngagement: "Both",
    },
    testimonials: [
      {
        id: "t15",
        reviewerName: "Marcus Rivera",
        reviewerRole: "Music Producer",
        reviewerCompany: "Harmony Records",
        reviewerAvatar: "/marcus-rivera.png",
        rating: 5,
        comment:
          "Sound Architect created an amazing collaborative music platform that revolutionized how our artists work together. The real-time audio processing is flawless, and the interface is incredibly intuitive. This has become an essential tool in our studio.",
        date: "2023-12-10",
        projectWorkedOn: "Collaborative Music Platform",
      },
    ],
    recentProjects: [
      {
        name: "Virtual Recording Studio",
        description:
          "A browser-based digital audio workstation with real-time collaboration features, allowing musicians to record, edit, and mix music together from anywhere.",
        tech: ["React", "Web Audio API", "WebRTC", "Node.js", "Socket.io", "TypeScript"],
        duration: "8 months",
        role: "Lead Developer",
        teamSize: "3 person team",
        outcome: "Used by 500+ musicians and featured in Music Tech Magazine",
      },
      {
        name: "Interactive Sound Visualizer",
        description:
          "An immersive audio-visual experience that creates stunning 3D visualizations in real-time based on music and sound input.",
        tech: ["Three.js", "Web Audio API", "WebGL", "React", "GLSL Shaders"],
        duration: "4 months",
        role: "Full-Stack Developer",
        teamSize: "2 person team",
        outcome: "Showcased at 5 major music festivals and art installations",
      },
    ],
    icon: Headphones,
    theme: {
      cardBg: "bg-gradient-to-br from-orange-900/80 to-red-900/80 backdrop-blur-md",
      border: "border-orange-500/30",
      headerBg: "bg-gradient-to-r from-orange-700 to-red-700",
      titleText: "text-orange-300",
      descText: "text-red-300",
      badgeBg: "bg-green-500/20",
      badgeText: "text-green-300",
      avatarBg: "bg-orange-500/20",
      skillBadge: "bg-orange-500/20 text-orange-300 border-orange-500/30",
      projectBg: "bg-orange-500/10",
      primaryButton: "bg-orange-600 hover:bg-orange-700 text-white",
      pattern: "bg-[radial-gradient(circle_at_50%_50%,rgba(249,115,22,0.1)_0%,transparent_50%)]",
    },
    socialLinks: {
      github: "https://github.com/soundarchitect",
      twitter: "https://twitter.com/audio_coder",
      linkedin: "https://linkedin.com/in/soundarchitect",
      website: "https://sound-interfaces.dev",
    },
  },
  // NEW CODERS ADDED BELOW
  // NEW CODERS - BATCH 2
  {
    id: "13",
    name: "Blockchain Sage",
    vibe: "Decentralized Future",
    platform: "desktop",
    bio: "Building the decentralized web with blockchain and Web3 technologies.",
    fullBio:
      "I'm passionate about creating decentralized applications that empower users and reshape digital ownership. With deep expertise in blockchain development, smart contracts, and Web3 technologies, I build applications that are transparent, secure, and user-owned. My work spans DeFi platforms, NFT marketplaces, and DAO governance systems.",
    location: "Singapore",
    timezone: "SGT",
    rating: 4.8,
    reviews: 67,
    projects: 23,
    likes: 198,
    status: "Available",
    avatar: "",
    themeIcon: "⛓️",
    skills: [
      "Solidity",
      "Web3.js",
      "Ethereum",
      "React",
      "Node.js",
      "IPFS",
      "Smart Contracts",
      "DeFi",
      "NFTs",
      "TypeScript",
    ],
    workExperience: [
      {
        company: "CryptoVentures",
        role: "Senior Blockchain Developer",
        duration: "2021 - Present",
        location: "Singapore",
        description:
          "Lead development of DeFi protocols and NFT marketplaces. Design and implement smart contracts with focus on security and gas optimization.",
        technologies: ["Solidity", "Web3.js", "React", "Node.js", "IPFS"],
        companyLogo: "/cryptoventures-logo.png",
      },
    ],
    compensation: {
      hourlyRate: "$100 - $180/hour",
      projectRate: "$15,000 - $60,000",
      availability: "30-40 hours/week",
      preferredEngagement: "Both",
    },
    testimonials: [
      {
        id: "t16",
        reviewerName: "Alex Chen",
        reviewerRole: "DeFi Protocol Founder",
        reviewerCompany: "YieldFarm Pro",
        reviewerAvatar: "/alex-chen.png",
        rating: 5,
        comment:
          "Blockchain Sage delivered a flawless DeFi protocol that has processed over $50M in transactions. Their smart contract security expertise is exceptional.",
        date: "2024-01-25",
        projectWorkedOn: "DeFi Yield Protocol",
      },
    ],
    recentProjects: [
      {
        name: "DeFi Yield Protocol",
        description:
          "A decentralized finance protocol for yield farming with automated strategies and risk management.",
        tech: ["Solidity", "Web3.js", "React", "Node.js", "Chainlink"],
        duration: "5 months",
        role: "Lead Blockchain Developer",
        teamSize: "4 person team",
        outcome: "Processed $50M+ in transactions with zero security incidents",
      },
    ],
    icon: Cpu,
    theme: {
      cardBg: "bg-gradient-to-br from-yellow-900/80 to-orange-900/80 backdrop-blur-md",
      border: "border-yellow-500/30",
      headerBg: "bg-gradient-to-r from-yellow-700 to-orange-700",
      titleText: "text-yellow-300",
      descText: "text-orange-300",
      badgeBg: "bg-green-500/20",
      badgeText: "text-green-300",
      avatarBg: "bg-yellow-500/20",
      skillBadge: "bg-yellow-500/20 text-yellow-300 border-yellow-500/30",
      projectBg: "bg-yellow-500/10",
      primaryButton: "bg-yellow-600 hover:bg-yellow-700 text-white",
      pattern: "bg-[radial-gradient(circle_at_50%_50%,rgba(245,158,11,0.1)_0%,transparent_50%)]",
    },
    socialLinks: {
      github: "https://github.com/blockchainsage",
      twitter: "https://twitter.com/web3_sage",
      linkedin: "https://linkedin.com/in/blockchainsage",
      website: "https://decentralized-dev.eth",
    },
  },
  {
    id: "14",
    name: "Data Wizard",
    vibe: "Analytics Sorcerer",
    platform: "desktop",
    bio: "Transforming raw data into magical insights and predictive models.",
    fullBio:
      "I specialize in data science and machine learning applications that reveal hidden patterns and predict future trends. With expertise in Python, R, and modern ML frameworks, I create intelligent systems that help businesses make data-driven decisions. My work spans from recommendation engines to predictive analytics platforms.",
    location: "London, UK",
    timezone: "GMT",
    rating: 4.9,
    reviews: 134,
    projects: 56,
    likes: 423,
    status: "Busy",
    avatar: "",
    themeIcon: "📊",
    skills: [
      "Python",
      "R",
      "TensorFlow",
      "PyTorch",
      "Pandas",
      "Scikit-learn",
      "SQL",
      "Tableau",
      "Apache Spark",
      "MLOps",
    ],
    workExperience: [
      {
        company: "DataMagic Analytics",
        role: "Senior Data Scientist",
        duration: "2020 - Present",
        location: "London, UK",
        description:
          "Lead data science initiatives for Fortune 500 companies. Develop machine learning models and data pipelines that drive business insights and automation.",
        technologies: ["Python", "TensorFlow", "Apache Spark", "SQL", "Docker"],
        companyLogo: "/datamagic-logo.png",
      },
    ],
    compensation: {
      hourlyRate: "$90 - $150/hour",
      projectRate: "$12,000 - $50,000",
      availability: "20-30 hours/week",
      preferredEngagement: "Project-based",
    },
    testimonials: [
      {
        id: "t17",
        reviewerName: "Sarah Williams",
        reviewerRole: "VP of Analytics",
        reviewerCompany: "RetailTech Corp",
        reviewerAvatar: "/sarah-williams.png",
        rating: 5,
        comment:
          "Data Wizard built us a recommendation engine that increased our sales by 40%. Their ability to translate complex data into actionable insights is remarkable.",
        date: "2023-12-20",
        projectWorkedOn: "E-commerce Recommendation Engine",
      },
    ],
    recentProjects: [
      {
        name: "Predictive Analytics Dashboard",
        description:
          "A comprehensive analytics platform that predicts customer behavior and market trends using advanced machine learning algorithms.",
        tech: ["Python", "TensorFlow", "React", "PostgreSQL", "Apache Spark"],
        duration: "6 months",
        role: "Lead Data Scientist",
        teamSize: "5 person team",
        outcome: "Improved prediction accuracy by 85% and reduced analysis time by 70%",
      },
    ],
    icon: Brain,
    theme: {
      cardBg: "bg-gradient-to-br from-indigo-900/80 to-blue-900/80 backdrop-blur-md",
      border: "border-indigo-500/30",
      headerBg: "bg-gradient-to-r from-indigo-700 to-blue-700",
      titleText: "text-indigo-300",
      descText: "text-blue-300",
      badgeBg: "bg-green-500/20",
      badgeText: "text-green-300",
      avatarBg: "bg-indigo-500/20",
      skillBadge: "bg-indigo-500/20 text-indigo-300 border-indigo-500/30",
      projectBg: "bg-indigo-500/10",
      primaryButton: "bg-indigo-600 hover:bg-indigo-700 text-white",
      pattern: "bg-[radial-gradient(circle_at_50%_50%,rgba(99,102,241,0.1)_0%,transparent_50%)]",
    },
    socialLinks: {
      github: "https://github.com/datawizard",
      linkedin: "https://linkedin.com/in/datawizard",
      website: "https://data-insights.ai",
    },
  },
  {
    id: "15",
    name: "Cloud Architect",
    vibe: "Infrastructure Maestro",
    platform: "desktop",
    bio: "Designing scalable cloud solutions that reach for the sky.",
    fullBio:
      "I architect and build cloud-native applications that scale effortlessly and perform reliably. With expertise in AWS, Azure, and Google Cloud, I create infrastructure that grows with your business. My focus is on microservices, containerization, and DevOps practices that enable rapid, reliable deployments.",
    location: "Seattle, WA",
    timezone: "PST",
    rating: 4.8,
    reviews: 98,
    projects: 44,
    likes: 267,
    status: "Available",
    avatar: "",
    themeIcon: "☁️",
    skills: [
      "AWS",
      "Docker",
      "Kubernetes",
      "Terraform",
      "Node.js",
      "Python",
      "Microservices",
      "DevOps",
      "CI/CD",
      "Monitoring",
    ],
    workExperience: [
      {
        company: "CloudScale Solutions",
        role: "Principal Cloud Architect",
        duration: "2019 - Present",
        location: "Seattle, WA",
        description:
          "Design and implement cloud infrastructure for enterprise clients. Lead migration projects and establish DevOps best practices for scalable, reliable systems.",
        technologies: ["AWS", "Kubernetes", "Terraform", "Docker", "Python"],
        companyLogo: "/cloudscale-logo.png",
      },
    ],
    compensation: {
      hourlyRate: "$110 - $180/hour",
      projectRate: "$15,000 - $75,000",
      availability: "25-35 hours/week",
      preferredEngagement: "Both",
    },
    testimonials: [
      {
        id: "t18",
        reviewerName: "Mark Thompson",
        reviewerRole: "CTO",
        reviewerCompany: "ScaleUp Tech",
        reviewerAvatar: "/mark-thompson.png",
        rating: 5,
        comment:
          "Cloud Architect transformed our infrastructure to handle 10x traffic growth. Their expertise in cloud architecture and DevOps is world-class.",
        date: "2024-02-10",
        projectWorkedOn: "Enterprise Cloud Migration",
      },
    ],
    recentProjects: [
      {
        name: "Microservices Platform",
        description:
          "A cloud-native microservices platform with auto-scaling, monitoring, and CI/CD pipelines for rapid deployment.",
        tech: ["AWS", "Kubernetes", "Docker", "Terraform", "Node.js"],
        duration: "8 months",
        role: "Lead Architect",
        teamSize: "6 person team",
        outcome: "Reduced deployment time by 90% and improved system reliability to 99.9%",
      },
    ],
    icon: Cpu,
    theme: {
      cardBg: "bg-gradient-to-br from-sky-900/80 to-blue-900/80 backdrop-blur-md",
      border: "border-sky-500/30",
      headerBg: "bg-gradient-to-r from-sky-700 to-blue-700",
      titleText: "text-sky-300",
      descText: "text-blue-300",
      badgeBg: "bg-green-500/20",
      badgeText: "text-green-300",
      avatarBg: "bg-sky-500/20",
      skillBadge: "bg-sky-500/20 text-sky-300 border-sky-500/30",
      projectBg: "bg-sky-500/10",
      primaryButton: "bg-sky-600 hover:bg-sky-700 text-white",
      pattern: "bg-[radial-gradient(circle_at_50%_50%,rgba(14,165,233,0.1)_0%,transparent_50%)]",
    },
    socialLinks: {
      github: "https://github.com/cloudarchitect",
      linkedin: "https://linkedin.com/in/cloudarchitect",
      website: "https://cloud-solutions.dev",
    },
  },
  // Continue adding more coders...
  {
    id: "16",
    name: "Mobile Maverick",
    vibe: "Cross-Platform Pioneer",
    platform: "mobile",
    bio: "Crafting seamless mobile experiences across iOS and Android.",
    fullBio:
      "I specialize in creating high-performance mobile applications that work flawlessly across platforms. With expertise in React Native, Flutter, and native development, I build apps that users love and businesses depend on. My focus is on performance optimization, user experience, and platform-specific features.",
    location: "Austin, TX",
    timezone: "CST",
    rating: 4.7,
    reviews: 89,
    projects: 52,
    likes: 234,
    status: "Available",
    avatar: "",
    themeIcon: "📱",
    skills: [
      "React Native",
      "Flutter",
      "Swift",
      "Kotlin",
      "TypeScript",
      "Firebase",
      "Redux",
      "Expo",
      "App Store Optimization",
      "Mobile UX",
    ],
    workExperience: [
      {
        company: "MobileFirst Studios",
        role: "Senior Mobile Developer",
        duration: "2020 - Present",
        location: "Austin, TX",
        description:
          "Lead mobile development for consumer and enterprise applications. Specialize in cross-platform solutions and performance optimization.",
        technologies: ["React Native", "Flutter", "Firebase", "Redux"],
        companyLogo: "/mobilefirst-logo.png",
      },
    ],
    compensation: {
      hourlyRate: "$80 - $130/hour",
      projectRate: "$8,000 - $40,000",
      availability: "35-45 hours/week",
      preferredEngagement: "Both",
    },
    testimonials: [
      {
        id: "t19",
        reviewerName: "Jennifer Lee",
        reviewerRole: "Product Manager",
        reviewerCompany: "FitTech App",
        reviewerAvatar: "/jennifer-lee.png",
        rating: 5,
        comment:
          "Mobile Maverick delivered our fitness app ahead of schedule with incredible performance. The app has maintained a 4.8 star rating across both platforms.",
        date: "2024-01-30",
        projectWorkedOn: "FitTracker Mobile App",
      },
    ],
    recentProjects: [
      {
        name: "FitTracker Pro",
        description:
          "A comprehensive fitness tracking app with workout planning, nutrition tracking, and social features.",
        tech: ["React Native", "Node.js", "Firebase", "Redux", "HealthKit"],
        duration: "6 months",
        role: "Lead Mobile Developer",
        teamSize: "4 person team",
        outcome: "Reached 100k+ downloads with 4.8 star rating",
      },
    ],
    icon: Smartphone,
    theme: {
      cardBg: "bg-gradient-to-br from-teal-900/80 to-cyan-900/80 backdrop-blur-md",
      border: "border-teal-500/30",
      headerBg: "bg-gradient-to-r from-teal-700 to-cyan-700",
      titleText: "text-teal-300",
      descText: "text-cyan-300",
      badgeBg: "bg-green-500/20",
      badgeText: "text-green-300",
      avatarBg: "bg-teal-500/20",
      skillBadge: "bg-teal-500/20 text-teal-300 border-teal-500/30",
      projectBg: "bg-teal-500/10",
      primaryButton: "bg-teal-600 hover:bg-teal-700 text-white",
      pattern: "bg-[radial-gradient(circle_at_50%_50%,rgba(20,184,166,0.1)_0%,transparent_50%)]",
    },
    socialLinks: {
      github: "https://github.com/mobilemaverick",
      twitter: "https://twitter.com/mobile_dev_pro",
      linkedin: "https://linkedin.com/in/mobilemaverick",
    },
  },
  {
    id: "17",
    name: "Security Guardian",
    vibe: "Cybersecurity Sentinel",
    platform: "desktop",
    bio: "Protecting digital realms with advanced security implementations.",
    fullBio:
      "I specialize in building secure applications and implementing robust cybersecurity measures. With expertise in penetration testing, secure coding practices, and compliance frameworks, I ensure applications are protected against modern threats. My work focuses on security architecture, vulnerability assessment, and secure development lifecycle.",
    location: "Washington, DC",
    timezone: "EST",
    rating: 4.9,
    reviews: 76,
    projects: 31,
    likes: 187,
    status: "Available",
    avatar: "",
    themeIcon: "🛡️",
    skills: [
      "Cybersecurity",
      "Penetration Testing",
      "OWASP",
      "Encryption",
      "OAuth",
      "JWT",
      "Security Auditing",
      "Compliance",
      "Node.js",
      "Python",
    ],
    workExperience: [
      {
        company: "SecureCode Solutions",
        role: "Senior Security Engineer",
        duration: "2019 - Present",
        location: "Washington, DC",
        description:
          "Lead security assessments and implement security measures for enterprise applications. Conduct penetration testing and security audits.",
        technologies: ["Python", "Node.js", "Security Tools", "OWASP", "Compliance"],
        companyLogo: "/securecode-logo.png",
      },
    ],
    compensation: {
      hourlyRate: "$120 - $200/hour",
      projectRate: "$15,000 - $80,000",
      availability: "25-35 hours/week",
      preferredEngagement: "Both",
    },
    testimonials: [
      {
        id: "t20",
        reviewerName: "Robert Kim",
        reviewerRole: "CISO",
        reviewerCompany: "FinanceSecure Corp",
        reviewerAvatar: "/robert-kim.png",
        rating: 5,
        comment:
          "Security Guardian identified and fixed critical vulnerabilities in our platform. Their security expertise is unmatched and they helped us achieve SOC 2 compliance.",
        date: "2023-11-25",
        projectWorkedOn: "Financial Platform Security Audit",
      },
    ],
    recentProjects: [
      {
        name: "Enterprise Security Platform",
        description:
          "A comprehensive security platform with threat detection, vulnerability scanning, and compliance reporting.",
        tech: ["Python", "Node.js", "Docker", "Kubernetes", "Security Tools"],
        duration: "7 months",
        role: "Lead Security Engineer",
        teamSize: "5 person team",
        outcome: "Reduced security incidents by 95% and achieved SOC 2 Type II compliance",
      },
    ],
    icon: Shield,
    theme: {
      cardBg: "bg-gradient-to-br from-red-900/80 to-orange-900/80 backdrop-blur-md",
      border: "border-red-500/30",
      headerBg: "bg-gradient-to-r from-red-700 to-orange-700",
      titleText: "text-red-300",
      descText: "text-orange-300",
      badgeBg: "bg-green-500/20",
      badgeText: "text-green-300",
      avatarBg: "bg-red-500/20",
      skillBadge: "bg-red-500/20 text-red-300 border-red-500/30",
      projectBg: "bg-red-500/10",
      primaryButton: "bg-red-600 hover:bg-red-700 text-white",
      pattern: "bg-[radial-gradient(circle_at_50%_50%,rgba(239,68,68,0.1)_0%,transparent_50%)]",
    },
    socialLinks: {
      github: "https://github.com/securityguardian",
      linkedin: "https://linkedin.com/in/securityguardian",
      website: "https://cybersec-expert.dev",
    },
  },
  // Add more coders...
]
