import { Palette, Zap, Sparkles, Gamepad2, Waves, Cpu, Leaf, Accessibility, Headphones } from "lucide-react"

// Transform the quest data to match the Quest interface
export const questData = [
  {
    id: "quest-1",
    title: "Quantum Trading Algorithm",
    description:
      "Develop a quantum-inspired trading algorithm for high-frequency financial markets with advanced risk management.",
    prize: "$25,000 - $40,000",
    status: "Featured" as const,
    postedBy: "Quantum Research Institute",
    postedByAvatar: "/quantum-research-institute-logo.png",
    skillsNeeded: ["Quantum Computing", "Python", "Financial Modeling", "Machine Learning", "Risk Management"],
    timeline: "4-6 months",
    vibe: "Futuristic Scientific",
    icon: Cpu,
    applicants: 12,
    theme: {
      cardBg: "bg-gradient-to-br from-slate-900/80 to-violet-900/80 backdrop-blur-md",
      border: "border-violet-500/30",
      titleText: "text-violet-300",
      descText: "text-slate-300",
      prizeText: "text-yellow-400",
      skillBadge: "bg-violet-500/20 text-violet-300 border-violet-500/30",
      primaryButton: "bg-violet-600 hover:bg-violet-700 text-white",
      iconBg: "bg-violet-500/20",
      pattern: "bg-[radial-gradient(circle_at_50%_50%,rgba(139,92,246,0.1)_0%,transparent_50%)]",
    },
  },
  {
    id: "quest-2",
    title: "Carbon Footprint Tracking Platform",
    description:
      "Build a comprehensive carbon tracking platform for e-commerce businesses to monitor and reduce their environmental impact.",
    prize: "$18,000 - $30,000",
    status: "Featured" as const,
    postedBy: "GreenShop Collective",
    postedByAvatar: "/greenshop-collective-logo.png",
    skillsNeeded: ["Sustainability Tech", "Vue.js", "Data Analytics", "API Integration", "Environmental Science"],
    timeline: "3-5 months",
    vibe: "Sustainable Technology",
    icon: Leaf,
    applicants: 18,
    theme: {
      cardBg: "bg-gradient-to-br from-emerald-900/80 to-teal-900/80 backdrop-blur-md",
      border: "border-emerald-500/30",
      titleText: "text-emerald-300",
      descText: "text-teal-300",
      prizeText: "text-yellow-400",
      skillBadge: "bg-emerald-500/20 text-emerald-300 border-emerald-500/30",
      primaryButton: "bg-emerald-600 hover:bg-emerald-700 text-white",
      iconBg: "bg-emerald-500/20",
      pattern: "bg-[radial-gradient(circle_at_50%_50%,rgba(16,185,129,0.1)_0%,transparent_50%)]",
    },
  },
  {
    id: "quest-3",
    title: "Accessible Learning Management System",
    description:
      "Design and develop a fully accessible LMS that meets WCAG 2.1 AAA standards for learners with diverse abilities.",
    prize: "$22,000 - $35,000",
    status: "Featured" as const,
    postedBy: "Digital Inclusion Foundation",
    postedByAvatar: "/digital-inclusion-foundation-logo.png",
    skillsNeeded: ["Accessibility", "WCAG", "React", "ARIA", "UX Design", "Assistive Technology"],
    timeline: "4-6 months",
    vibe: "Inclusive Design",
    icon: Accessibility,
    applicants: 8,
    theme: {
      cardBg: "bg-gradient-to-br from-blue-900/80 to-purple-900/80 backdrop-blur-md",
      border: "border-blue-500/30",
      titleText: "text-blue-300",
      descText: "text-purple-300",
      prizeText: "text-yellow-400",
      skillBadge: "bg-blue-500/20 text-blue-300 border-blue-500/30",
      primaryButton: "bg-blue-600 hover:bg-blue-700 text-white",
      iconBg: "bg-blue-500/20",
      pattern: "bg-[radial-gradient(circle_at_50%_50%,rgba(59,130,246,0.1)_0%,transparent_50%)]",
    },
  },
  {
    id: "quest-4",
    title: "Retro Gaming Arcade Platform",
    description:
      "Build a web-based retro gaming platform with authentic 80s arcade experience and modern social features.",
    prize: "$15,000 - $25,000",
    status: "Open" as const,
    postedBy: "Neon Entertainment",
    postedByAvatar: "/neon-entertainment-logo.png",
    skillsNeeded: ["Game Development", "WebGL", "JavaScript", "Emulation", "WebRTC", "Canvas API"],
    timeline: "3-4 months",
    vibe: "80s Arcade Nostalgia",
    icon: Gamepad2,
    applicants: 22,
    theme: {
      cardBg: "bg-gradient-to-br from-pink-900/80 to-orange-900/80 backdrop-blur-md",
      border: "border-pink-500/30",
      titleText: "text-pink-400",
      descText: "text-orange-400",
      prizeText: "text-yellow-400",
      skillBadge: "bg-pink-500/20 text-pink-400 border-pink-500/30",
      primaryButton: "bg-pink-600 hover:bg-pink-700 text-white",
      iconBg: "bg-pink-500/20",
      pattern: "bg-[radial-gradient(circle_at_50%_50%,rgba(236,72,153,0.1)_0%,transparent_50%)]",
    },
  },
  {
    id: "quest-5",
    title: "Mindfulness & Wellness Mobile App",
    description:
      "Develop a comprehensive wellness app with guided meditations, biometric integration, and personalized mindfulness journeys.",
    prize: "$20,000 - $32,000",
    status: "Open" as const,
    postedBy: "Peaceful Mind Studios",
    postedByAvatar: "/peaceful-mind-studios-logo.png",
    skillsNeeded: [
      "React Native",
      "Wellness Tech",
      "HealthKit",
      "Biometric Integration",
      "UX Design",
      "Audio Processing",
    ],
    timeline: "4-5 months",
    vibe: "Audio-Visual Harmony",
    icon: Headphones,
    applicants: 16,
    theme: {
      cardBg: "bg-gradient-to-br from-orange-900/80 to-red-900/80 backdrop-blur-md",
      border: "border-orange-500/30",
      titleText: "text-orange-300",
      descText: "text-red-300",
      prizeText: "text-yellow-400",
      skillBadge: "bg-orange-500/20 text-orange-300 border-orange-500/30",
      primaryButton: "bg-orange-600 hover:bg-orange-700 text-white",
      iconBg: "bg-orange-500/20",
      pattern: "bg-[radial-gradient(circle_at_50%_50%,rgba(249,115,22,0.1)_0%,transparent_50%)]",
    },
  },
  // Add more existing quests to match the original data structure
  {
    id: "quest-6",
    title: "Mystical Animation Studio Platform",
    description:
      "Create a collaborative platform for animators with real-time editing, version control, and magical workflow automation.",
    prize: "$30,000 - $45,000",
    status: "Featured" as const,
    postedBy: "Mystic Animations Co.",
    postedByAvatar: "/mystic-animations-co-logo.png",
    skillsNeeded: ["React", "WebGL", "Animation", "Real-time Collaboration", "Video Processing"],
    timeline: "6-8 months",
    vibe: "Whimsical Studio Ghibli",
    icon: Palette,
    applicants: 14,
    theme: {
      cardBg: "bg-ghibli-dark/70 backdrop-blur-sm",
      border: "border-purple-500/30",
      titleText: "text-ghibli-blue",
      descText: "text-ghibli-purple",
      prizeText: "text-ghibli-green",
      skillBadge: "bg-ghibli-cyan/20 text-ghibli-cyan border-ghibli-cyan/30",
      primaryButton: "bg-ghibli-blue hover:bg-ghibli-blue/90 text-ghibli-darker font-semibold",
      iconBg: "bg-purple-500/20",
      pattern: "bg-[radial-gradient(circle_at_50%_50%,rgba(123,104,238,0.05)_0%,transparent_60%)]",
    },
  },
  {
    id: "quest-7",
    title: "Cyberpunk Social Network",
    description:
      "Build a next-gen social platform with encrypted messaging, AR integration, and neon-lit user experiences.",
    prize: "$35,000 - $50,000",
    status: "Open" as const,
    postedBy: "NeonTech Innovations",
    postedByAvatar: "/innovatech-solutions-logo.png",
    skillsNeeded: ["React Native", "Encryption", "AR/VR", "Real-time Systems", "Blockchain"],
    timeline: "8-10 months",
    vibe: "Cyberpunk Retro",
    icon: Zap,
    applicants: 28,
    theme: {
      cardBg: "bg-gradient-to-br from-green-900/80 to-cyan-900/80 backdrop-blur-md",
      border: "border-green-500/30",
      titleText: "text-green-300",
      descText: "text-green-200",
      prizeText: "text-ghibli-green",
      skillBadge: "bg-green-500/20 text-green-300 border-green-500/30",
      primaryButton: "bg-green-600 hover:bg-green-700 text-white",
      iconBg: "bg-green-500/20",
      pattern: "bg-[radial-gradient(circle_at_50%_50%,rgba(34,197,94,0.1)_0%,transparent_50%)]",
    },
  },
  {
    id: "quest-8",
    title: "Celestial Data Observatory",
    description:
      "Develop an astronomical data visualization platform with real-time telescope integration and cosmic insights.",
    prize: "$28,000 - $42,000",
    status: "Featured" as const,
    postedBy: "Starlight Research",
    postedByAvatar: "/dreamweaver-studios-logo.png",
    skillsNeeded: ["Data Visualization", "Three.js", "Real-time Processing", "Scientific Computing", "WebGL"],
    timeline: "5-7 months",
    vibe: "Celestial Mystical",
    icon: Sparkles,
    applicants: 19,
    theme: {
      cardBg: "bg-gradient-to-br from-indigo-900/80 to-purple-900/80 backdrop-blur-md",
      border: "border-indigo-500/30",
      titleText: "text-indigo-300",
      descText: "text-indigo-200",
      prizeText: "text-ghibli-green",
      skillBadge: "bg-indigo-500/20 text-indigo-300 border-indigo-500/30",
      primaryButton: "bg-indigo-600 hover:bg-indigo-700 text-white",
      iconBg: "bg-indigo-500/20",
      pattern: "bg-[radial-gradient(circle_at_50%_50%,rgba(99,102,241,0.1)_0%,transparent_50%)]",
    },
  },
  {
    id: "quest-9",
    title: "Retro Game Development Suite",
    description:
      "Create a comprehensive game development platform with pixel art tools, sound synthesis, and publishing pipeline.",
    prize: "$25,000 - $38,000",
    status: "Open" as const,
    postedBy: "8-Bit Legends",
    postedByAvatar: "/8-bit-legends-logo.png",
    skillsNeeded: ["Game Development", "Pixel Art Tools", "Audio Synthesis", "WebAssembly", "Canvas API"],
    timeline: "6-8 months",
    vibe: "80s Arcade Nostalgia",
    icon: Gamepad2,
    applicants: 31,
    theme: {
      cardBg: "bg-gradient-to-br from-pink-900/80 to-orange-900/80 backdrop-blur-md",
      border: "border-pink-500/30",
      titleText: "text-pink-400",
      descText: "text-orange-400",
      prizeText: "text-ghibli-green",
      skillBadge: "bg-pink-500/20 text-pink-400 border-pink-500/30",
      primaryButton: "bg-pink-600 hover:bg-pink-700 text-white",
      iconBg: "bg-pink-500/20",
      pattern: "bg-[radial-gradient(circle_at_50%_50%,rgba(236,72,153,0.1)_0%,transparent_50%)]",
    },
  },
  {
    id: "quest-10",
    title: "Ocean Conservation Tracker",
    description: "Build a marine life monitoring system with underwater sensor integration and conservation analytics.",
    prize: "$32,000 - $48,000",
    status: "Featured" as const,
    postedBy: "Ocean Guardians Initiative",
    postedByAvatar: "/placeholder-hj52r.png",
    skillsNeeded: ["IoT Integration", "Environmental Data", "React", "Data Analytics", "Marine Biology"],
    timeline: "7-9 months",
    vibe: "Aquatic Serenity",
    icon: Waves,
    applicants: 15,
    theme: {
      cardBg: "bg-gradient-to-br from-blue-900/80 to-cyan-900/80 backdrop-blur-md",
      border: "border-blue-500/30",
      titleText: "text-blue-300",
      descText: "text-cyan-300",
      prizeText: "text-ghibli-green",
      skillBadge: "bg-blue-500/20 text-blue-300 border-blue-500/30",
      primaryButton: "bg-blue-600 hover:bg-blue-700 text-white",
      iconBg: "bg-blue-500/20",
      pattern: "bg-[radial-gradient(circle_at_50%_50%,rgba(59,130,246,0.1)_0%,transparent_50%)]",
    },
  },
]
